### ISSUE TITLE
Good job, thank you 

### ISSUE THREAD

**Issue by danielo515** [saadmk11/comment-website-screenshot#5]
Buddy, very good work! This is awesome.
In a place that feels like the wild wild west, full of badly documented actions, crappy ones, actions that do not work or that are built for one person very specific use case  finding a gem like this just feels awesome.
It worked out of the box, with the provided example configuration and does exactly what I expect it to do: I'm impressed. Took me more time to find it than using it, and that is already a compliment to it. I love how it takes advantage of the features of github without requiring you to use anything else.
Very, very good job, thank you.

One little question, does it keep the history of screenshot or is the branch overwritten?
Regards

**Comment by saadmk11** [comment]
Hi @danielo515,
This GitHub Action keeps all the images in the new branch that it has created. For example you can check this out: https://github.com/saadmk11/node-express-demo/tree/website-screenshots-action-branch/website-screenshots

**Comment by danielo515** [comment]
That's awesome. Thanks
